#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="etimetracklite1")]
public partial class EliteDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertDevice(Device instance);
  partial void UpdateDevice(Device instance);
  partial void DeleteDevice(Device instance);
  partial void InsertDeviceCommand(DeviceCommand instance);
  partial void UpdateDeviceCommand(DeviceCommand instance);
  partial void DeleteDeviceCommand(DeviceCommand instance);
  partial void InsertEmployeesBio(EmployeesBio instance);
  partial void UpdateEmployeesBio(EmployeesBio instance);
  partial void DeleteEmployeesBio(EmployeesBio instance);
  partial void InsertEmployee(Employee instance);
  partial void UpdateEmployee(Employee instance);
  partial void DeleteEmployee(Employee instance);
  #endregion
	
	public EliteDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["etimetracklite1ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public EliteDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public EliteDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public EliteDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public EliteDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Device> Devices
	{
		get
		{
			return this.GetTable<Device>();
		}
	}
	
	public System.Data.Linq.Table<DeviceCommand> DeviceCommands
	{
		get
		{
			return this.GetTable<DeviceCommand>();
		}
	}
	
	public System.Data.Linq.Table<EmployeesBio> EmployeesBios
	{
		get
		{
			return this.GetTable<EmployeesBio>();
		}
	}
	
	public System.Data.Linq.Table<Employee> Employees
	{
		get
		{
			return this.GetTable<Employee>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Devices")]
public partial class Device : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _DeviceId;
	
	private string _DeviceFName;
	
	private string _DeviceSName;
	
	private string _DeviceDirection;
	
	private string _SerialNumber;
	
	private string _ConnectionType;
	
	private string _IpAddress;
	
	private string _BaudRate;
	
	private string _CommKey;
	
	private string _ComPort;
	
	private System.Nullable<System.DateTime> _LastLogDownloadDate;
	
	private string _C1;
	
	private string _C2;
	
	private string _C3;
	
	private string _C4;
	
	private string _C5;
	
	private string _C6;
	
	private string _C7;
	
	private string _TransactionStamp;
	
	private System.Nullable<System.DateTime> _LastPing;
	
	private string _DeviceType;
	
	private string _OpStamp;
	
	private System.Nullable<int> _DownLoadType;
	
	private string _Timezone;
	
	private string _DeviceLocation;
	
	private string _TimeOut;
	
	private string _FaceDeviceType;
	
	private System.Nullable<int> _MasterId;
	
	private string _AttPhotoStamp;
	
	private string _DeviceActivationCode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceIdChanging(int value);
    partial void OnDeviceIdChanged();
    partial void OnDeviceFNameChanging(string value);
    partial void OnDeviceFNameChanged();
    partial void OnDeviceSNameChanging(string value);
    partial void OnDeviceSNameChanged();
    partial void OnDeviceDirectionChanging(string value);
    partial void OnDeviceDirectionChanged();
    partial void OnSerialNumberChanging(string value);
    partial void OnSerialNumberChanged();
    partial void OnConnectionTypeChanging(string value);
    partial void OnConnectionTypeChanged();
    partial void OnIpAddressChanging(string value);
    partial void OnIpAddressChanged();
    partial void OnBaudRateChanging(string value);
    partial void OnBaudRateChanged();
    partial void OnCommKeyChanging(string value);
    partial void OnCommKeyChanged();
    partial void OnComPortChanging(string value);
    partial void OnComPortChanged();
    partial void OnLastLogDownloadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLogDownloadDateChanged();
    partial void OnC1Changing(string value);
    partial void OnC1Changed();
    partial void OnC2Changing(string value);
    partial void OnC2Changed();
    partial void OnC3Changing(string value);
    partial void OnC3Changed();
    partial void OnC4Changing(string value);
    partial void OnC4Changed();
    partial void OnC5Changing(string value);
    partial void OnC5Changed();
    partial void OnC6Changing(string value);
    partial void OnC6Changed();
    partial void OnC7Changing(string value);
    partial void OnC7Changed();
    partial void OnTransactionStampChanging(string value);
    partial void OnTransactionStampChanged();
    partial void OnLastPingChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPingChanged();
    partial void OnDeviceTypeChanging(string value);
    partial void OnDeviceTypeChanged();
    partial void OnOpStampChanging(string value);
    partial void OnOpStampChanged();
    partial void OnDownLoadTypeChanging(System.Nullable<int> value);
    partial void OnDownLoadTypeChanged();
    partial void OnTimezoneChanging(string value);
    partial void OnTimezoneChanged();
    partial void OnDeviceLocationChanging(string value);
    partial void OnDeviceLocationChanged();
    partial void OnTimeOutChanging(string value);
    partial void OnTimeOutChanged();
    partial void OnFaceDeviceTypeChanging(string value);
    partial void OnFaceDeviceTypeChanged();
    partial void OnMasterIdChanging(System.Nullable<int> value);
    partial void OnMasterIdChanged();
    partial void OnAttPhotoStampChanging(string value);
    partial void OnAttPhotoStampChanged();
    partial void OnDeviceActivationCodeChanging(string value);
    partial void OnDeviceActivationCodeChanged();
    #endregion
	
	public Device()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int DeviceId
	{
		get
		{
			return this._DeviceId;
		}
		set
		{
			if ((this._DeviceId != value))
			{
				this.OnDeviceIdChanging(value);
				this.SendPropertyChanging();
				this._DeviceId = value;
				this.SendPropertyChanged("DeviceId");
				this.OnDeviceIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceFName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string DeviceFName
	{
		get
		{
			return this._DeviceFName;
		}
		set
		{
			if ((this._DeviceFName != value))
			{
				this.OnDeviceFNameChanging(value);
				this.SendPropertyChanging();
				this._DeviceFName = value;
				this.SendPropertyChanged("DeviceFName");
				this.OnDeviceFNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceSName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string DeviceSName
	{
		get
		{
			return this._DeviceSName;
		}
		set
		{
			if ((this._DeviceSName != value))
			{
				this.OnDeviceSNameChanging(value);
				this.SendPropertyChanging();
				this._DeviceSName = value;
				this.SendPropertyChanged("DeviceSName");
				this.OnDeviceSNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceDirection", DbType="NVarChar(255)")]
	public string DeviceDirection
	{
		get
		{
			return this._DeviceDirection;
		}
		set
		{
			if ((this._DeviceDirection != value))
			{
				this.OnDeviceDirectionChanging(value);
				this.SendPropertyChanging();
				this._DeviceDirection = value;
				this.SendPropertyChanged("DeviceDirection");
				this.OnDeviceDirectionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(255)")]
	public string SerialNumber
	{
		get
		{
			return this._SerialNumber;
		}
		set
		{
			if ((this._SerialNumber != value))
			{
				this.OnSerialNumberChanging(value);
				this.SendPropertyChanging();
				this._SerialNumber = value;
				this.SendPropertyChanged("SerialNumber");
				this.OnSerialNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionType", DbType="NVarChar(255)")]
	public string ConnectionType
	{
		get
		{
			return this._ConnectionType;
		}
		set
		{
			if ((this._ConnectionType != value))
			{
				this.OnConnectionTypeChanging(value);
				this.SendPropertyChanging();
				this._ConnectionType = value;
				this.SendPropertyChanged("ConnectionType");
				this.OnConnectionTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpAddress", DbType="NVarChar(255)")]
	public string IpAddress
	{
		get
		{
			return this._IpAddress;
		}
		set
		{
			if ((this._IpAddress != value))
			{
				this.OnIpAddressChanging(value);
				this.SendPropertyChanging();
				this._IpAddress = value;
				this.SendPropertyChanged("IpAddress");
				this.OnIpAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaudRate", DbType="NVarChar(255)")]
	public string BaudRate
	{
		get
		{
			return this._BaudRate;
		}
		set
		{
			if ((this._BaudRate != value))
			{
				this.OnBaudRateChanging(value);
				this.SendPropertyChanging();
				this._BaudRate = value;
				this.SendPropertyChanged("BaudRate");
				this.OnBaudRateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommKey", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string CommKey
	{
		get
		{
			return this._CommKey;
		}
		set
		{
			if ((this._CommKey != value))
			{
				this.OnCommKeyChanging(value);
				this.SendPropertyChanging();
				this._CommKey = value;
				this.SendPropertyChanged("CommKey");
				this.OnCommKeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComPort", DbType="NVarChar(255)")]
	public string ComPort
	{
		get
		{
			return this._ComPort;
		}
		set
		{
			if ((this._ComPort != value))
			{
				this.OnComPortChanging(value);
				this.SendPropertyChanging();
				this._ComPort = value;
				this.SendPropertyChanged("ComPort");
				this.OnComPortChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogDownloadDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> LastLogDownloadDate
	{
		get
		{
			return this._LastLogDownloadDate;
		}
		set
		{
			if ((this._LastLogDownloadDate != value))
			{
				this.OnLastLogDownloadDateChanging(value);
				this.SendPropertyChanging();
				this._LastLogDownloadDate = value;
				this.SendPropertyChanged("LastLogDownloadDate");
				this.OnLastLogDownloadDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C1", DbType="NVarChar(255)")]
	public string C1
	{
		get
		{
			return this._C1;
		}
		set
		{
			if ((this._C1 != value))
			{
				this.OnC1Changing(value);
				this.SendPropertyChanging();
				this._C1 = value;
				this.SendPropertyChanged("C1");
				this.OnC1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C2", DbType="NVarChar(255)")]
	public string C2
	{
		get
		{
			return this._C2;
		}
		set
		{
			if ((this._C2 != value))
			{
				this.OnC2Changing(value);
				this.SendPropertyChanging();
				this._C2 = value;
				this.SendPropertyChanged("C2");
				this.OnC2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C3", DbType="NVarChar(255)")]
	public string C3
	{
		get
		{
			return this._C3;
		}
		set
		{
			if ((this._C3 != value))
			{
				this.OnC3Changing(value);
				this.SendPropertyChanging();
				this._C3 = value;
				this.SendPropertyChanged("C3");
				this.OnC3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C4", DbType="NVarChar(255)")]
	public string C4
	{
		get
		{
			return this._C4;
		}
		set
		{
			if ((this._C4 != value))
			{
				this.OnC4Changing(value);
				this.SendPropertyChanging();
				this._C4 = value;
				this.SendPropertyChanged("C4");
				this.OnC4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C5", DbType="NVarChar(255)")]
	public string C5
	{
		get
		{
			return this._C5;
		}
		set
		{
			if ((this._C5 != value))
			{
				this.OnC5Changing(value);
				this.SendPropertyChanging();
				this._C5 = value;
				this.SendPropertyChanged("C5");
				this.OnC5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C6", DbType="NVarChar(255)")]
	public string C6
	{
		get
		{
			return this._C6;
		}
		set
		{
			if ((this._C6 != value))
			{
				this.OnC6Changing(value);
				this.SendPropertyChanging();
				this._C6 = value;
				this.SendPropertyChanged("C6");
				this.OnC6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C7", DbType="NVarChar(255)")]
	public string C7
	{
		get
		{
			return this._C7;
		}
		set
		{
			if ((this._C7 != value))
			{
				this.OnC7Changing(value);
				this.SendPropertyChanging();
				this._C7 = value;
				this.SendPropertyChanged("C7");
				this.OnC7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionStamp", DbType="NVarChar(50)")]
	public string TransactionStamp
	{
		get
		{
			return this._TransactionStamp;
		}
		set
		{
			if ((this._TransactionStamp != value))
			{
				this.OnTransactionStampChanging(value);
				this.SendPropertyChanging();
				this._TransactionStamp = value;
				this.SendPropertyChanged("TransactionStamp");
				this.OnTransactionStampChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPing", DbType="DateTime")]
	public System.Nullable<System.DateTime> LastPing
	{
		get
		{
			return this._LastPing;
		}
		set
		{
			if ((this._LastPing != value))
			{
				this.OnLastPingChanging(value);
				this.SendPropertyChanging();
				this._LastPing = value;
				this.SendPropertyChanged("LastPing");
				this.OnLastPingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceType", DbType="NVarChar(255)")]
	public string DeviceType
	{
		get
		{
			return this._DeviceType;
		}
		set
		{
			if ((this._DeviceType != value))
			{
				this.OnDeviceTypeChanging(value);
				this.SendPropertyChanging();
				this._DeviceType = value;
				this.SendPropertyChanged("DeviceType");
				this.OnDeviceTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpStamp", DbType="NVarChar(255)")]
	public string OpStamp
	{
		get
		{
			return this._OpStamp;
		}
		set
		{
			if ((this._OpStamp != value))
			{
				this.OnOpStampChanging(value);
				this.SendPropertyChanging();
				this._OpStamp = value;
				this.SendPropertyChanged("OpStamp");
				this.OnOpStampChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownLoadType", DbType="Int")]
	public System.Nullable<int> DownLoadType
	{
		get
		{
			return this._DownLoadType;
		}
		set
		{
			if ((this._DownLoadType != value))
			{
				this.OnDownLoadTypeChanging(value);
				this.SendPropertyChanging();
				this._DownLoadType = value;
				this.SendPropertyChanged("DownLoadType");
				this.OnDownLoadTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timezone", DbType="NVarChar(50)")]
	public string Timezone
	{
		get
		{
			return this._Timezone;
		}
		set
		{
			if ((this._Timezone != value))
			{
				this.OnTimezoneChanging(value);
				this.SendPropertyChanging();
				this._Timezone = value;
				this.SendPropertyChanged("Timezone");
				this.OnTimezoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceLocation", DbType="NVarChar(50)")]
	public string DeviceLocation
	{
		get
		{
			return this._DeviceLocation;
		}
		set
		{
			if ((this._DeviceLocation != value))
			{
				this.OnDeviceLocationChanging(value);
				this.SendPropertyChanging();
				this._DeviceLocation = value;
				this.SendPropertyChanged("DeviceLocation");
				this.OnDeviceLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOut", DbType="NVarChar(50)")]
	public string TimeOut
	{
		get
		{
			return this._TimeOut;
		}
		set
		{
			if ((this._TimeOut != value))
			{
				this.OnTimeOutChanging(value);
				this.SendPropertyChanging();
				this._TimeOut = value;
				this.SendPropertyChanged("TimeOut");
				this.OnTimeOutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceDeviceType", DbType="NVarChar(255)")]
	public string FaceDeviceType
	{
		get
		{
			return this._FaceDeviceType;
		}
		set
		{
			if ((this._FaceDeviceType != value))
			{
				this.OnFaceDeviceTypeChanging(value);
				this.SendPropertyChanging();
				this._FaceDeviceType = value;
				this.SendPropertyChanged("FaceDeviceType");
				this.OnFaceDeviceTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterId", DbType="Int")]
	public System.Nullable<int> MasterId
	{
		get
		{
			return this._MasterId;
		}
		set
		{
			if ((this._MasterId != value))
			{
				this.OnMasterIdChanging(value);
				this.SendPropertyChanging();
				this._MasterId = value;
				this.SendPropertyChanged("MasterId");
				this.OnMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttPhotoStamp", DbType="NVarChar(255)")]
	public string AttPhotoStamp
	{
		get
		{
			return this._AttPhotoStamp;
		}
		set
		{
			if ((this._AttPhotoStamp != value))
			{
				this.OnAttPhotoStampChanging(value);
				this.SendPropertyChanging();
				this._AttPhotoStamp = value;
				this.SendPropertyChanged("AttPhotoStamp");
				this.OnAttPhotoStampChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceActivationCode", DbType="NVarChar(50)")]
	public string DeviceActivationCode
	{
		get
		{
			return this._DeviceActivationCode;
		}
		set
		{
			if ((this._DeviceActivationCode != value))
			{
				this.OnDeviceActivationCodeChanging(value);
				this.SendPropertyChanging();
				this._DeviceActivationCode = value;
				this.SendPropertyChanged("DeviceActivationCode");
				this.OnDeviceActivationCodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceCommands")]
public partial class DeviceCommand : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _DeviceCommandId;
	
	private string _Title;
	
	private string _DeviceCommand1;
	
	private string _SerialNumber;
	
	private string _Status;
	
	private string _Type;
	
	private System.Nullable<System.DateTime> _CreationDate;
	
	private System.Nullable<System.DateTime> _ExecutionDate;
	
	private string _DeviceCommandFace;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceCommandIdChanging(int value);
    partial void OnDeviceCommandIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDeviceCommand1Changing(string value);
    partial void OnDeviceCommand1Changed();
    partial void OnSerialNumberChanging(string value);
    partial void OnSerialNumberChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnCreationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationDateChanged();
    partial void OnExecutionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExecutionDateChanged();
    partial void OnDeviceCommandFaceChanging(string value);
    partial void OnDeviceCommandFaceChanged();
    #endregion
	
	public DeviceCommand()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceCommandId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int DeviceCommandId
	{
		get
		{
			return this._DeviceCommandId;
		}
		set
		{
			if ((this._DeviceCommandId != value))
			{
				this.OnDeviceCommandIdChanging(value);
				this.SendPropertyChanging();
				this._DeviceCommandId = value;
				this.SendPropertyChanged("DeviceCommandId");
				this.OnDeviceCommandIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DeviceCommand", Storage="_DeviceCommand1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string DeviceCommand1
	{
		get
		{
			return this._DeviceCommand1;
		}
		set
		{
			if ((this._DeviceCommand1 != value))
			{
				this.OnDeviceCommand1Changing(value);
				this.SendPropertyChanging();
				this._DeviceCommand1 = value;
				this.SendPropertyChanged("DeviceCommand1");
				this.OnDeviceCommand1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(255)")]
	public string SerialNumber
	{
		get
		{
			return this._SerialNumber;
		}
		set
		{
			if ((this._SerialNumber != value))
			{
				this.OnSerialNumberChanging(value);
				this.SendPropertyChanging();
				this._SerialNumber = value;
				this.SendPropertyChanged("SerialNumber");
				this.OnSerialNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(255)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreationDate
	{
		get
		{
			return this._CreationDate;
		}
		set
		{
			if ((this._CreationDate != value))
			{
				this.OnCreationDateChanging(value);
				this.SendPropertyChanging();
				this._CreationDate = value;
				this.SendPropertyChanged("CreationDate");
				this.OnCreationDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutionDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ExecutionDate
	{
		get
		{
			return this._ExecutionDate;
		}
		set
		{
			if ((this._ExecutionDate != value))
			{
				this.OnExecutionDateChanging(value);
				this.SendPropertyChanging();
				this._ExecutionDate = value;
				this.SendPropertyChanged("ExecutionDate");
				this.OnExecutionDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceCommandFace", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string DeviceCommandFace
	{
		get
		{
			return this._DeviceCommandFace;
		}
		set
		{
			if ((this._DeviceCommandFace != value))
			{
				this.OnDeviceCommandFaceChanging(value);
				this.SendPropertyChanging();
				this._DeviceCommandFace = value;
				this.SendPropertyChanged("DeviceCommandFace");
				this.OnDeviceCommandFaceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeesBio")]
public partial class EmployeesBio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _EmployeeBioId;
	
	private int _EmployeeId;
	
	private string _BioType;
	
	private string _BioVersion;
	
	private int _BioId;
	
	private string _Bio;
	
	private string _FaceBio1;
	
	private string _FaceBio2;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeBioIdChanging(int value);
    partial void OnEmployeeBioIdChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnBioTypeChanging(string value);
    partial void OnBioTypeChanged();
    partial void OnBioVersionChanging(string value);
    partial void OnBioVersionChanged();
    partial void OnBioIdChanging(int value);
    partial void OnBioIdChanged();
    partial void OnBioChanging(string value);
    partial void OnBioChanged();
    partial void OnFaceBio1Changing(string value);
    partial void OnFaceBio1Changed();
    partial void OnFaceBio2Changing(string value);
    partial void OnFaceBio2Changed();
    #endregion
	
	public EmployeesBio()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeBioId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int EmployeeBioId
	{
		get
		{
			return this._EmployeeBioId;
		}
		set
		{
			if ((this._EmployeeBioId != value))
			{
				this.OnEmployeeBioIdChanging(value);
				this.SendPropertyChanging();
				this._EmployeeBioId = value;
				this.SendPropertyChanged("EmployeeBioId");
				this.OnEmployeeBioIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int EmployeeId
	{
		get
		{
			return this._EmployeeId;
		}
		set
		{
			if ((this._EmployeeId != value))
			{
				this.OnEmployeeIdChanging(value);
				this.SendPropertyChanging();
				this._EmployeeId = value;
				this.SendPropertyChanged("EmployeeId");
				this.OnEmployeeIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BioType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string BioType
	{
		get
		{
			return this._BioType;
		}
		set
		{
			if ((this._BioType != value))
			{
				this.OnBioTypeChanging(value);
				this.SendPropertyChanging();
				this._BioType = value;
				this.SendPropertyChanged("BioType");
				this.OnBioTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BioVersion", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string BioVersion
	{
		get
		{
			return this._BioVersion;
		}
		set
		{
			if ((this._BioVersion != value))
			{
				this.OnBioVersionChanging(value);
				this.SendPropertyChanging();
				this._BioVersion = value;
				this.SendPropertyChanged("BioVersion");
				this.OnBioVersionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BioId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int BioId
	{
		get
		{
			return this._BioId;
		}
		set
		{
			if ((this._BioId != value))
			{
				this.OnBioIdChanging(value);
				this.SendPropertyChanging();
				this._BioId = value;
				this.SendPropertyChanged("BioId");
				this.OnBioIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bio", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Bio
	{
		get
		{
			return this._Bio;
		}
		set
		{
			if ((this._Bio != value))
			{
				this.OnBioChanging(value);
				this.SendPropertyChanging();
				this._Bio = value;
				this.SendPropertyChanged("Bio");
				this.OnBioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceBio1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string FaceBio1
	{
		get
		{
			return this._FaceBio1;
		}
		set
		{
			if ((this._FaceBio1 != value))
			{
				this.OnFaceBio1Changing(value);
				this.SendPropertyChanging();
				this._FaceBio1 = value;
				this.SendPropertyChanged("FaceBio1");
				this.OnFaceBio1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceBio2", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string FaceBio2
	{
		get
		{
			return this._FaceBio2;
		}
		set
		{
			if ((this._FaceBio2 != value))
			{
				this.OnFaceBio2Changing(value);
				this.SendPropertyChanging();
				this._FaceBio2 = value;
				this.SendPropertyChanged("FaceBio2");
				this.OnFaceBio2Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _EmployeeId;
	
	private string _EmployeeName;
	
	private string _EmployeeCode;
	
	private string _StringCode;
	
	private int _NumericCode;
	
	private string _Gender;
	
	private int _CompanyId;
	
	private int _DepartmentId;
	
	private string _Designation;
	
	private int _CategoryId;
	
	private System.Nullable<System.DateTime> _DOJ;
	
	private System.Nullable<System.DateTime> _DOR;
	
	private System.Nullable<System.DateTime> _DOC;
	
	private string _EmployeeCodeInDevice;
	
	private string _EmployeeRFIDNumber;
	
	private string _EmployementType;
	
	private string _Status;
	
	private string _EmployeeDevicePassword;
	
	private string _EmployeeDeviceGroup;
	
	private string _FatherName;
	
	private string _MotherName;
	
	private string _ResidentialAddress;
	
	private string _PermanentAddress;
	
	private string _ContactNo;
	
	private string _Email;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _PlaceOfBirth;
	
	private string _Nomenee1;
	
	private string _Nomenee2;
	
	private string _Remarks;
	
	private System.Nullable<int> _RecordStatus;
	
	private string _C1;
	
	private string _C2;
	
	private string _C3;
	
	private string _C4;
	
	private string _C5;
	
	private string _C6;
	
	private string _C7;
	
	private string _Location;
	
	private string _BLOODGROUP;
	
	private string _WorkPlace;
	
	private string _ExtensionNo;
	
	private string _LoginName;
	
	private string _LoginPassword;
	
	private string _Grade;
	
	private string _Team;
	
	private System.Nullable<int> _IsRecieveNotification;
	
	private System.Nullable<int> _HolidayGroup;
	
	private System.Nullable<int> _ShiftGroupId;
	
	private System.Nullable<int> _ShiftRosterId;
	
	private string _LastModifiedBy;
	
	private string _AadhaarNumber;
	
	private System.Data.Linq.Binary _EmployeePhoto;
	
	private System.Nullable<int> _MasterDeviceId;
	
	private string _BIOPhoto1;
	
	private System.Data.Linq.Binary _BIOPhotoPic;
	
	private System.Nullable<int> _DeviceExpiryRule;
	
	private System.Nullable<System.DateTime> _DeviceExpiryStartDate;
	
	private System.Nullable<System.DateTime> _DeviceExpiryEndDate;
	
	private System.Nullable<int> _DeviceId;
	
	private System.Nullable<System.DateTime> _EnrolledDate;
	
	private System.Nullable<int> _MigrateToOtherCryptography;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnEmployeeCodeChanging(string value);
    partial void OnEmployeeCodeChanged();
    partial void OnStringCodeChanging(string value);
    partial void OnStringCodeChanged();
    partial void OnNumericCodeChanging(int value);
    partial void OnNumericCodeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnCompanyIdChanging(int value);
    partial void OnCompanyIdChanged();
    partial void OnDepartmentIdChanging(int value);
    partial void OnDepartmentIdChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnDOJChanging(System.Nullable<System.DateTime> value);
    partial void OnDOJChanged();
    partial void OnDORChanging(System.Nullable<System.DateTime> value);
    partial void OnDORChanged();
    partial void OnDOCChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCChanged();
    partial void OnEmployeeCodeInDeviceChanging(string value);
    partial void OnEmployeeCodeInDeviceChanged();
    partial void OnEmployeeRFIDNumberChanging(string value);
    partial void OnEmployeeRFIDNumberChanged();
    partial void OnEmployementTypeChanging(string value);
    partial void OnEmployementTypeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnEmployeeDevicePasswordChanging(string value);
    partial void OnEmployeeDevicePasswordChanged();
    partial void OnEmployeeDeviceGroupChanging(string value);
    partial void OnEmployeeDeviceGroupChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnMotherNameChanging(string value);
    partial void OnMotherNameChanged();
    partial void OnResidentialAddressChanging(string value);
    partial void OnResidentialAddressChanged();
    partial void OnPermanentAddressChanging(string value);
    partial void OnPermanentAddressChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnPlaceOfBirthChanging(string value);
    partial void OnPlaceOfBirthChanged();
    partial void OnNomenee1Changing(string value);
    partial void OnNomenee1Changed();
    partial void OnNomenee2Changing(string value);
    partial void OnNomenee2Changed();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnRecordStatusChanging(System.Nullable<int> value);
    partial void OnRecordStatusChanged();
    partial void OnC1Changing(string value);
    partial void OnC1Changed();
    partial void OnC2Changing(string value);
    partial void OnC2Changed();
    partial void OnC3Changing(string value);
    partial void OnC3Changed();
    partial void OnC4Changing(string value);
    partial void OnC4Changed();
    partial void OnC5Changing(string value);
    partial void OnC5Changed();
    partial void OnC6Changing(string value);
    partial void OnC6Changed();
    partial void OnC7Changing(string value);
    partial void OnC7Changed();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnBLOODGROUPChanging(string value);
    partial void OnBLOODGROUPChanged();
    partial void OnWorkPlaceChanging(string value);
    partial void OnWorkPlaceChanged();
    partial void OnExtensionNoChanging(string value);
    partial void OnExtensionNoChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnLoginPasswordChanging(string value);
    partial void OnLoginPasswordChanged();
    partial void OnGradeChanging(string value);
    partial void OnGradeChanged();
    partial void OnTeamChanging(string value);
    partial void OnTeamChanged();
    partial void OnIsRecieveNotificationChanging(System.Nullable<int> value);
    partial void OnIsRecieveNotificationChanged();
    partial void OnHolidayGroupChanging(System.Nullable<int> value);
    partial void OnHolidayGroupChanged();
    partial void OnShiftGroupIdChanging(System.Nullable<int> value);
    partial void OnShiftGroupIdChanged();
    partial void OnShiftRosterIdChanging(System.Nullable<int> value);
    partial void OnShiftRosterIdChanged();
    partial void OnLastModifiedByChanging(string value);
    partial void OnLastModifiedByChanged();
    partial void OnAadhaarNumberChanging(string value);
    partial void OnAadhaarNumberChanged();
    partial void OnEmployeePhotoChanging(System.Data.Linq.Binary value);
    partial void OnEmployeePhotoChanged();
    partial void OnMasterDeviceIdChanging(System.Nullable<int> value);
    partial void OnMasterDeviceIdChanged();
    partial void OnBIOPhoto1Changing(string value);
    partial void OnBIOPhoto1Changed();
    partial void OnBIOPhotoPicChanging(System.Data.Linq.Binary value);
    partial void OnBIOPhotoPicChanged();
    partial void OnDeviceExpiryRuleChanging(System.Nullable<int> value);
    partial void OnDeviceExpiryRuleChanged();
    partial void OnDeviceExpiryStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeviceExpiryStartDateChanged();
    partial void OnDeviceExpiryEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeviceExpiryEndDateChanged();
    partial void OnDeviceIdChanging(System.Nullable<int> value);
    partial void OnDeviceIdChanged();
    partial void OnEnrolledDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnrolledDateChanged();
    partial void OnMigrateToOtherCryptographyChanging(System.Nullable<int> value);
    partial void OnMigrateToOtherCryptographyChanged();
    #endregion
	
	public Employee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int EmployeeId
	{
		get
		{
			return this._EmployeeId;
		}
		set
		{
			if ((this._EmployeeId != value))
			{
				this.OnEmployeeIdChanging(value);
				this.SendPropertyChanging();
				this._EmployeeId = value;
				this.SendPropertyChanged("EmployeeId");
				this.OnEmployeeIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string EmployeeCode
	{
		get
		{
			return this._EmployeeCode;
		}
		set
		{
			if ((this._EmployeeCode != value))
			{
				this.OnEmployeeCodeChanging(value);
				this.SendPropertyChanging();
				this._EmployeeCode = value;
				this.SendPropertyChanged("EmployeeCode");
				this.OnEmployeeCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string StringCode
	{
		get
		{
			return this._StringCode;
		}
		set
		{
			if ((this._StringCode != value))
			{
				this.OnStringCodeChanging(value);
				this.SendPropertyChanging();
				this._StringCode = value;
				this.SendPropertyChanged("StringCode");
				this.OnStringCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumericCode", DbType="Int NOT NULL")]
	public int NumericCode
	{
		get
		{
			return this._NumericCode;
		}
		set
		{
			if ((this._NumericCode != value))
			{
				this.OnNumericCodeChanging(value);
				this.SendPropertyChanging();
				this._NumericCode = value;
				this.SendPropertyChanged("NumericCode");
				this.OnNumericCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int NOT NULL")]
	public int CompanyId
	{
		get
		{
			return this._CompanyId;
		}
		set
		{
			if ((this._CompanyId != value))
			{
				this.OnCompanyIdChanging(value);
				this.SendPropertyChanging();
				this._CompanyId = value;
				this.SendPropertyChanged("CompanyId");
				this.OnCompanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="Int NOT NULL")]
	public int DepartmentId
	{
		get
		{
			return this._DepartmentId;
		}
		set
		{
			if ((this._DepartmentId != value))
			{
				this.OnDepartmentIdChanging(value);
				this.SendPropertyChanging();
				this._DepartmentId = value;
				this.SendPropertyChanged("DepartmentId");
				this.OnDepartmentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(255)")]
	public string Designation
	{
		get
		{
			return this._Designation;
		}
		set
		{
			if ((this._Designation != value))
			{
				this.OnDesignationChanging(value);
				this.SendPropertyChanging();
				this._Designation = value;
				this.SendPropertyChanged("Designation");
				this.OnDesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int NOT NULL")]
	public int CategoryId
	{
		get
		{
			return this._CategoryId;
		}
		set
		{
			if ((this._CategoryId != value))
			{
				this.OnCategoryIdChanging(value);
				this.SendPropertyChanging();
				this._CategoryId = value;
				this.SendPropertyChanged("CategoryId");
				this.OnCategoryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOJ", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOJ
	{
		get
		{
			return this._DOJ;
		}
		set
		{
			if ((this._DOJ != value))
			{
				this.OnDOJChanging(value);
				this.SendPropertyChanging();
				this._DOJ = value;
				this.SendPropertyChanged("DOJ");
				this.OnDOJChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOR", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOR
	{
		get
		{
			return this._DOR;
		}
		set
		{
			if ((this._DOR != value))
			{
				this.OnDORChanging(value);
				this.SendPropertyChanging();
				this._DOR = value;
				this.SendPropertyChanged("DOR");
				this.OnDORChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOC
	{
		get
		{
			return this._DOC;
		}
		set
		{
			if ((this._DOC != value))
			{
				this.OnDOCChanging(value);
				this.SendPropertyChanging();
				this._DOC = value;
				this.SendPropertyChanged("DOC");
				this.OnDOCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeCodeInDevice", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string EmployeeCodeInDevice
	{
		get
		{
			return this._EmployeeCodeInDevice;
		}
		set
		{
			if ((this._EmployeeCodeInDevice != value))
			{
				this.OnEmployeeCodeInDeviceChanging(value);
				this.SendPropertyChanging();
				this._EmployeeCodeInDevice = value;
				this.SendPropertyChanged("EmployeeCodeInDevice");
				this.OnEmployeeCodeInDeviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeRFIDNumber", DbType="NVarChar(255)")]
	public string EmployeeRFIDNumber
	{
		get
		{
			return this._EmployeeRFIDNumber;
		}
		set
		{
			if ((this._EmployeeRFIDNumber != value))
			{
				this.OnEmployeeRFIDNumberChanging(value);
				this.SendPropertyChanging();
				this._EmployeeRFIDNumber = value;
				this.SendPropertyChanged("EmployeeRFIDNumber");
				this.OnEmployeeRFIDNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployementType", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string EmployementType
	{
		get
		{
			return this._EmployementType;
		}
		set
		{
			if ((this._EmployementType != value))
			{
				this.OnEmployementTypeChanging(value);
				this.SendPropertyChanging();
				this._EmployementType = value;
				this.SendPropertyChanged("EmployementType");
				this.OnEmployementTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeDevicePassword", DbType="NVarChar(50)")]
	public string EmployeeDevicePassword
	{
		get
		{
			return this._EmployeeDevicePassword;
		}
		set
		{
			if ((this._EmployeeDevicePassword != value))
			{
				this.OnEmployeeDevicePasswordChanging(value);
				this.SendPropertyChanging();
				this._EmployeeDevicePassword = value;
				this.SendPropertyChanged("EmployeeDevicePassword");
				this.OnEmployeeDevicePasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeDeviceGroup", DbType="NVarChar(50)")]
	public string EmployeeDeviceGroup
	{
		get
		{
			return this._EmployeeDeviceGroup;
		}
		set
		{
			if ((this._EmployeeDeviceGroup != value))
			{
				this.OnEmployeeDeviceGroupChanging(value);
				this.SendPropertyChanging();
				this._EmployeeDeviceGroup = value;
				this.SendPropertyChanged("EmployeeDeviceGroup");
				this.OnEmployeeDeviceGroupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(255)")]
	public string FatherName
	{
		get
		{
			return this._FatherName;
		}
		set
		{
			if ((this._FatherName != value))
			{
				this.OnFatherNameChanging(value);
				this.SendPropertyChanging();
				this._FatherName = value;
				this.SendPropertyChanged("FatherName");
				this.OnFatherNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(255)")]
	public string MotherName
	{
		get
		{
			return this._MotherName;
		}
		set
		{
			if ((this._MotherName != value))
			{
				this.OnMotherNameChanging(value);
				this.SendPropertyChanging();
				this._MotherName = value;
				this.SendPropertyChanged("MotherName");
				this.OnMotherNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResidentialAddress", DbType="NVarChar(255)")]
	public string ResidentialAddress
	{
		get
		{
			return this._ResidentialAddress;
		}
		set
		{
			if ((this._ResidentialAddress != value))
			{
				this.OnResidentialAddressChanging(value);
				this.SendPropertyChanging();
				this._ResidentialAddress = value;
				this.SendPropertyChanged("ResidentialAddress");
				this.OnResidentialAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentAddress", DbType="NVarChar(255)")]
	public string PermanentAddress
	{
		get
		{
			return this._PermanentAddress;
		}
		set
		{
			if ((this._PermanentAddress != value))
			{
				this.OnPermanentAddressChanging(value);
				this.SendPropertyChanging();
				this._PermanentAddress = value;
				this.SendPropertyChanged("PermanentAddress");
				this.OnPermanentAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="NVarChar(255)")]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfBirth", DbType="NVarChar(255)")]
	public string PlaceOfBirth
	{
		get
		{
			return this._PlaceOfBirth;
		}
		set
		{
			if ((this._PlaceOfBirth != value))
			{
				this.OnPlaceOfBirthChanging(value);
				this.SendPropertyChanging();
				this._PlaceOfBirth = value;
				this.SendPropertyChanged("PlaceOfBirth");
				this.OnPlaceOfBirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomenee1", DbType="NVarChar(255)")]
	public string Nomenee1
	{
		get
		{
			return this._Nomenee1;
		}
		set
		{
			if ((this._Nomenee1 != value))
			{
				this.OnNomenee1Changing(value);
				this.SendPropertyChanging();
				this._Nomenee1 = value;
				this.SendPropertyChanged("Nomenee1");
				this.OnNomenee1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomenee2", DbType="NVarChar(255)")]
	public string Nomenee2
	{
		get
		{
			return this._Nomenee2;
		}
		set
		{
			if ((this._Nomenee2 != value))
			{
				this.OnNomenee2Changing(value);
				this.SendPropertyChanging();
				this._Nomenee2 = value;
				this.SendPropertyChanged("Nomenee2");
				this.OnNomenee2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Remarks
	{
		get
		{
			return this._Remarks;
		}
		set
		{
			if ((this._Remarks != value))
			{
				this.OnRemarksChanging(value);
				this.SendPropertyChanging();
				this._Remarks = value;
				this.SendPropertyChanged("Remarks");
				this.OnRemarksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordStatus", DbType="Int")]
	public System.Nullable<int> RecordStatus
	{
		get
		{
			return this._RecordStatus;
		}
		set
		{
			if ((this._RecordStatus != value))
			{
				this.OnRecordStatusChanging(value);
				this.SendPropertyChanging();
				this._RecordStatus = value;
				this.SendPropertyChanged("RecordStatus");
				this.OnRecordStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C1", DbType="NVarChar(255)")]
	public string C1
	{
		get
		{
			return this._C1;
		}
		set
		{
			if ((this._C1 != value))
			{
				this.OnC1Changing(value);
				this.SendPropertyChanging();
				this._C1 = value;
				this.SendPropertyChanged("C1");
				this.OnC1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C2", DbType="NVarChar(255)")]
	public string C2
	{
		get
		{
			return this._C2;
		}
		set
		{
			if ((this._C2 != value))
			{
				this.OnC2Changing(value);
				this.SendPropertyChanging();
				this._C2 = value;
				this.SendPropertyChanged("C2");
				this.OnC2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C3", DbType="NVarChar(255)")]
	public string C3
	{
		get
		{
			return this._C3;
		}
		set
		{
			if ((this._C3 != value))
			{
				this.OnC3Changing(value);
				this.SendPropertyChanging();
				this._C3 = value;
				this.SendPropertyChanged("C3");
				this.OnC3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C4", DbType="NVarChar(255)")]
	public string C4
	{
		get
		{
			return this._C4;
		}
		set
		{
			if ((this._C4 != value))
			{
				this.OnC4Changing(value);
				this.SendPropertyChanging();
				this._C4 = value;
				this.SendPropertyChanged("C4");
				this.OnC4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C5", DbType="NVarChar(255)")]
	public string C5
	{
		get
		{
			return this._C5;
		}
		set
		{
			if ((this._C5 != value))
			{
				this.OnC5Changing(value);
				this.SendPropertyChanging();
				this._C5 = value;
				this.SendPropertyChanged("C5");
				this.OnC5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C6", DbType="NVarChar(255)")]
	public string C6
	{
		get
		{
			return this._C6;
		}
		set
		{
			if ((this._C6 != value))
			{
				this.OnC6Changing(value);
				this.SendPropertyChanging();
				this._C6 = value;
				this.SendPropertyChanged("C6");
				this.OnC6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C7", DbType="NVarChar(255)")]
	public string C7
	{
		get
		{
			return this._C7;
		}
		set
		{
			if ((this._C7 != value))
			{
				this.OnC7Changing(value);
				this.SendPropertyChanging();
				this._C7 = value;
				this.SendPropertyChanged("C7");
				this.OnC7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(255)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOODGROUP", DbType="NVarChar(255)")]
	public string BLOODGROUP
	{
		get
		{
			return this._BLOODGROUP;
		}
		set
		{
			if ((this._BLOODGROUP != value))
			{
				this.OnBLOODGROUPChanging(value);
				this.SendPropertyChanging();
				this._BLOODGROUP = value;
				this.SendPropertyChanged("BLOODGROUP");
				this.OnBLOODGROUPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPlace", DbType="NVarChar(255)")]
	public string WorkPlace
	{
		get
		{
			return this._WorkPlace;
		}
		set
		{
			if ((this._WorkPlace != value))
			{
				this.OnWorkPlaceChanging(value);
				this.SendPropertyChanging();
				this._WorkPlace = value;
				this.SendPropertyChanged("WorkPlace");
				this.OnWorkPlaceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionNo", DbType="NVarChar(255)")]
	public string ExtensionNo
	{
		get
		{
			return this._ExtensionNo;
		}
		set
		{
			if ((this._ExtensionNo != value))
			{
				this.OnExtensionNoChanging(value);
				this.SendPropertyChanging();
				this._ExtensionNo = value;
				this.SendPropertyChanged("ExtensionNo");
				this.OnExtensionNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="NVarChar(255)")]
	public string LoginName
	{
		get
		{
			return this._LoginName;
		}
		set
		{
			if ((this._LoginName != value))
			{
				this.OnLoginNameChanging(value);
				this.SendPropertyChanging();
				this._LoginName = value;
				this.SendPropertyChanged("LoginName");
				this.OnLoginNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginPassword", DbType="NVarChar(255)")]
	public string LoginPassword
	{
		get
		{
			return this._LoginPassword;
		}
		set
		{
			if ((this._LoginPassword != value))
			{
				this.OnLoginPasswordChanging(value);
				this.SendPropertyChanging();
				this._LoginPassword = value;
				this.SendPropertyChanged("LoginPassword");
				this.OnLoginPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
	public string Grade
	{
		get
		{
			return this._Grade;
		}
		set
		{
			if ((this._Grade != value))
			{
				this.OnGradeChanging(value);
				this.SendPropertyChanging();
				this._Grade = value;
				this.SendPropertyChanged("Grade");
				this.OnGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team", DbType="NVarChar(255)")]
	public string Team
	{
		get
		{
			return this._Team;
		}
		set
		{
			if ((this._Team != value))
			{
				this.OnTeamChanging(value);
				this.SendPropertyChanging();
				this._Team = value;
				this.SendPropertyChanged("Team");
				this.OnTeamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRecieveNotification", DbType="Int")]
	public System.Nullable<int> IsRecieveNotification
	{
		get
		{
			return this._IsRecieveNotification;
		}
		set
		{
			if ((this._IsRecieveNotification != value))
			{
				this.OnIsRecieveNotificationChanging(value);
				this.SendPropertyChanging();
				this._IsRecieveNotification = value;
				this.SendPropertyChanged("IsRecieveNotification");
				this.OnIsRecieveNotificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HolidayGroup", DbType="Int")]
	public System.Nullable<int> HolidayGroup
	{
		get
		{
			return this._HolidayGroup;
		}
		set
		{
			if ((this._HolidayGroup != value))
			{
				this.OnHolidayGroupChanging(value);
				this.SendPropertyChanging();
				this._HolidayGroup = value;
				this.SendPropertyChanged("HolidayGroup");
				this.OnHolidayGroupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftGroupId", DbType="Int")]
	public System.Nullable<int> ShiftGroupId
	{
		get
		{
			return this._ShiftGroupId;
		}
		set
		{
			if ((this._ShiftGroupId != value))
			{
				this.OnShiftGroupIdChanging(value);
				this.SendPropertyChanging();
				this._ShiftGroupId = value;
				this.SendPropertyChanged("ShiftGroupId");
				this.OnShiftGroupIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftRosterId", DbType="Int")]
	public System.Nullable<int> ShiftRosterId
	{
		get
		{
			return this._ShiftRosterId;
		}
		set
		{
			if ((this._ShiftRosterId != value))
			{
				this.OnShiftRosterIdChanging(value);
				this.SendPropertyChanging();
				this._ShiftRosterId = value;
				this.SendPropertyChanged("ShiftRosterId");
				this.OnShiftRosterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedBy", DbType="NVarChar(50)")]
	public string LastModifiedBy
	{
		get
		{
			return this._LastModifiedBy;
		}
		set
		{
			if ((this._LastModifiedBy != value))
			{
				this.OnLastModifiedByChanging(value);
				this.SendPropertyChanging();
				this._LastModifiedBy = value;
				this.SendPropertyChanged("LastModifiedBy");
				this.OnLastModifiedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadhaarNumber", DbType="NVarChar(255)")]
	public string AadhaarNumber
	{
		get
		{
			return this._AadhaarNumber;
		}
		set
		{
			if ((this._AadhaarNumber != value))
			{
				this.OnAadhaarNumberChanging(value);
				this.SendPropertyChanging();
				this._AadhaarNumber = value;
				this.SendPropertyChanged("AadhaarNumber");
				this.OnAadhaarNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeePhoto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary EmployeePhoto
	{
		get
		{
			return this._EmployeePhoto;
		}
		set
		{
			if ((this._EmployeePhoto != value))
			{
				this.OnEmployeePhotoChanging(value);
				this.SendPropertyChanging();
				this._EmployeePhoto = value;
				this.SendPropertyChanged("EmployeePhoto");
				this.OnEmployeePhotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterDeviceId", DbType="Int")]
	public System.Nullable<int> MasterDeviceId
	{
		get
		{
			return this._MasterDeviceId;
		}
		set
		{
			if ((this._MasterDeviceId != value))
			{
				this.OnMasterDeviceIdChanging(value);
				this.SendPropertyChanging();
				this._MasterDeviceId = value;
				this.SendPropertyChanged("MasterDeviceId");
				this.OnMasterDeviceIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPhoto1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string BIOPhoto1
	{
		get
		{
			return this._BIOPhoto1;
		}
		set
		{
			if ((this._BIOPhoto1 != value))
			{
				this.OnBIOPhoto1Changing(value);
				this.SendPropertyChanging();
				this._BIOPhoto1 = value;
				this.SendPropertyChanged("BIOPhoto1");
				this.OnBIOPhoto1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIOPhotoPic", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary BIOPhotoPic
	{
		get
		{
			return this._BIOPhotoPic;
		}
		set
		{
			if ((this._BIOPhotoPic != value))
			{
				this.OnBIOPhotoPicChanging(value);
				this.SendPropertyChanging();
				this._BIOPhotoPic = value;
				this.SendPropertyChanged("BIOPhotoPic");
				this.OnBIOPhotoPicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceExpiryRule", DbType="Int")]
	public System.Nullable<int> DeviceExpiryRule
	{
		get
		{
			return this._DeviceExpiryRule;
		}
		set
		{
			if ((this._DeviceExpiryRule != value))
			{
				this.OnDeviceExpiryRuleChanging(value);
				this.SendPropertyChanging();
				this._DeviceExpiryRule = value;
				this.SendPropertyChanged("DeviceExpiryRule");
				this.OnDeviceExpiryRuleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceExpiryStartDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeviceExpiryStartDate
	{
		get
		{
			return this._DeviceExpiryStartDate;
		}
		set
		{
			if ((this._DeviceExpiryStartDate != value))
			{
				this.OnDeviceExpiryStartDateChanging(value);
				this.SendPropertyChanging();
				this._DeviceExpiryStartDate = value;
				this.SendPropertyChanged("DeviceExpiryStartDate");
				this.OnDeviceExpiryStartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceExpiryEndDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeviceExpiryEndDate
	{
		get
		{
			return this._DeviceExpiryEndDate;
		}
		set
		{
			if ((this._DeviceExpiryEndDate != value))
			{
				this.OnDeviceExpiryEndDateChanging(value);
				this.SendPropertyChanging();
				this._DeviceExpiryEndDate = value;
				this.SendPropertyChanged("DeviceExpiryEndDate");
				this.OnDeviceExpiryEndDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Int")]
	public System.Nullable<int> DeviceId
	{
		get
		{
			return this._DeviceId;
		}
		set
		{
			if ((this._DeviceId != value))
			{
				this.OnDeviceIdChanging(value);
				this.SendPropertyChanging();
				this._DeviceId = value;
				this.SendPropertyChanged("DeviceId");
				this.OnDeviceIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrolledDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EnrolledDate
	{
		get
		{
			return this._EnrolledDate;
		}
		set
		{
			if ((this._EnrolledDate != value))
			{
				this.OnEnrolledDateChanging(value);
				this.SendPropertyChanging();
				this._EnrolledDate = value;
				this.SendPropertyChanged("EnrolledDate");
				this.OnEnrolledDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MigrateToOtherCryptography", DbType="Int")]
	public System.Nullable<int> MigrateToOtherCryptography
	{
		get
		{
			return this._MigrateToOtherCryptography;
		}
		set
		{
			if ((this._MigrateToOtherCryptography != value))
			{
				this.OnMigrateToOtherCryptographyChanging(value);
				this.SendPropertyChanging();
				this._MigrateToOtherCryptography = value;
				this.SendPropertyChanged("MigrateToOtherCryptography");
				this.OnMigrateToOtherCryptographyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
